Raise on JRuby 1.7.3 warning Celluloid is broken
After helping someone debug this *again* today I think our best bet is
to simply have Celluloid raise if someone tries to require it on JRuby
1.7.3:

    $ bundle exec irb -rcelluloid
    RuntimeError: Celluloid is broken on JRuby 1.7.3. Please upgrade to
    1.7.4+